



 export const NIGERIAN_BANKS = [
  { name: "78 Finance Company Ltd", code: "40195", slug: "78-finance-company-ltd-ng", longcode: "110072" },
  { name: "9mobile 9Payment Service Bank", code: "120001", slug: "9mobile-9payment-service-bank-ng", longcode: "120001" },
  { name: "Abbey Mortgage Bank", code: "404", slug: "abbey-mortgage-bank-ng", longcode: "" },
  { name: "Above Only MFB", code: "51204", slug: "above-only-mfb", longcode: "" },
  { name: "Abulesoro MFB", code: "51312", slug: "abulesoro-mfb-ng", longcode: "" },
  { name: "Access Bank", code: "044", slug: "access-bank", longcode: "044150149" },
  { name: "Access Bank (Diamond)", code: "063", slug: "access-bank-diamond", longcode: "063150162" },
  { name: "Accion Microfinance Bank", code: "602", slug: "accion-microfinance-bank-ng", longcode: "" },
  { name: "Aella MFB", code: "50315", slug: "aella-mfb-ng", longcode: "50315" },
  { name: "AG Mortgage Bank", code: "90077", slug: "ag-mortgage-bank-ng", longcode: "100028" },
  { name: "Ahmadu Bello University Microfinance Bank", code: "50036", slug: "ahmadu-bello-university-microfinance-bank-ng", longcode: "" },
  { name: "Airtel Smartcash PSB", code: "120004", slug: "airtel-smartcash-psb-ng", longcode: "120004" },
  { name: "AKU Microfinance Bank", code: "51336", slug: "aku-mfb", longcode: "" },
  { name: "Akuchukwu Microfinance Bank Limited", code: "090561", slug: "akuchukwu-microfinance-bank-limited-ng", longcode: "090561" },
  { name: "Al-Barakah Microfinance Bank", code: "50055", slug: "al-barakah-microfinance-bank-ng", longcode: "090133" },
  { name: "ALAT by WEMA", code: "035A", slug: "alat-by-wema", longcode: "035150103" },
  { name: "Alpha Morgan Bank", code: "108", slug: "alpha-morgan", longcode: "000041" },
  { name: "Alternative bank", code: "000304", slug: "the-alternative-bank-ng", longcode: "000304" },
  { name: "Amegy Microfinance Bank", code: "090629", slug: "amegy-microfinance-bank-ng", longcode: "090629" },
  { name: "Amju Unique MFB", code: "50926", slug: "amju-unique-mfb", longcode: "511080896" },
  { name: "Aramoko MFB", code: "50083", slug: "aramoko-mfb", longcode: "" },
  { name: "ASO Savings and Loans", code: "401", slug: "asosavings", longcode: "" },
  { name: "Assets Microfinance Bank", code: "50092", slug: "assets-microfinance-bank-ng", longcode: "50092" },
  { name: "Astrapolaris MFB LTD", code: "MFB50094", slug: "astrapolaris-mfb", longcode: "" },
  { name: "AVUENEGBE MICROFINANCE BANK", code: "090478", slug: "avuenegbe-microfinance-bank-ng", longcode: "090478" },
  { name: "AWACASH MICROFINANCE BANK", code: "51351", slug: "awacash-microfinance-bank-ng", longcode: "51351" },
  { name: "AZTEC MICROFINANCE BANK LIMITED", code: "51337", slug: "aztec-microfinance-bank-limited-ng", longcode: "090540" },
  { name: "Bainescredit MFB", code: "51229", slug: "bainescredit-mfb", longcode: "" },
  { name: "Banc Corp Microfinance Bank", code: "50117", slug: "banc-corp-microfinance-bank-ng", longcode: "50117" },
  { name: "BANKIT MICROFINANCE BANK LTD", code: "50572", slug: "bankit-microfinance-bank-ltd-ng", longcode: "090275" },
  { name: "BANKLY MFB", code: "51341", slug: "ampersand-microfinance-bank-ng", longcode: "" },
  { name: "Baobab Microfinance Bank", code: "MFB50992", slug: "baobab-microfinance-bank-ng", longcode: "MFB50992" },
  { name: "BellBank Microfinance Bank", code: "51100", slug: "bellbank-microfinance-bank-ng", longcode: "51100" },
  { name: "Benysta Microfinance Bank Limited", code: "51267", slug: "benysta-microfinance-bank-limited", longcode: "51267" },
  { name: "Beststar Microfinance Bank", code: "50123", slug: "beststar-microfinance-bank-ng", longcode: "090615" },
  { name: "BOLD MFB", code: "50725", slug: "bold-mfb-ng", longcode: "090753" },
  { name: "Bosak Microfinance Bank", code: "650", slug: "bosak-microfinance-bank-ng", longcode: "650" },
  { name: "Bowen Microfinance Bank", code: "50931", slug: "bowen-microfinance-bank", longcode: "" },
  { name: "Branch International Finance Company Limited", code: "FC40163", slug: "branch", longcode: "" },
  { name: "Brent Mortgage bank", code: "90070", slug: "brent-mortgage-bank-ng", longcode: "070015" },
  { name: "BuyPower MFB", code: "50645", slug: "buypower-mfb-ng", longcode: "50645" },
  { name: "Carbon", code: "565", slug: "carbon", longcode: "" },
  { name: "Cashbridge Microfinance Bank Limited", code: "51353", slug: "cashbridge-mfb-ng", longcode: "51353" },
  { name: "CASHCONNECT MFB", code: "865", slug: "cashconnect-mfb-ng", longcode: "865" },
  { name: "CEMCS Microfinance Bank", code: "50823", slug: "cemcs-microfinance-bank", longcode: "" },
  { name: "Chanelle Microfinance Bank Limited", code: "50171", slug: "chanelle-microfinance-bank-limited-ng", longcode: "50171" },
  { name: "Chikum Microfinance bank", code: "312", slug: "chikum-microfinance-bank-ng", longcode: null },
  { name: "Citibank Nigeria", code: "023", slug: "citibank-nigeria", longcode: "023150005" },
  { name: "CITYCODE MORTGAGE BANK", code: "070027", slug: "citycode-mortage-bank-ng", longcode: "070027" },
  { name: "Consumer Microfinance Bank", code: "50910", slug: "consumer-microfinance-bank-ng", longcode: "50910" },
  { name: "Cool Microfinance Bank Limited", code: "51458", slug: "cool-microfinance-bank-limited-ng", longcode: "090842" },
  { name: "Corestep MFB", code: "50204", slug: "corestep-mfb", longcode: "" },
  { name: "Coronation Merchant Bank", code: "559", slug: "coronation-merchant-bank-ng", longcode: "" },
  { name: "County Finance Limited", code: "FC40128", slug: "county-finance-limited", longcode: "" },
  { name: "Credit Direct Limited", code: "40119", slug: "credit-direct-limited-ng", longcode: "110049" },
  { name: "Crescent MFB", code: "51297", slug: "crescent-mfb", longcode: "" },
  { name: "Crust Microfinance Bank", code: "090560", slug: "crust-microfinance-bank-ng", longcode: "" },
  { name: "CRUTECH MICROFINANCE BANK LTD", code: "50216", slug: "crutech-microfinance-bank-ltd-ng", longcode: "090414" },
  { name: "Dash Microfinance Bank", code: "51368", slug: "dash-microfinance-bank-ng", longcode: "090845" },
  { name: "Davenport MICROFINANCE BANK", code: "51334", slug: "davenport-microfinance-bank-ng", longcode: "51334" },
  { name: "Dillon Microfinance Bank", code: "51450", slug: "dillon-microfinance-bank-ng", longcode: "09828" },
  { name: "Dot Microfinance Bank", code: "50162", slug: "dot-microfinance-bank-ng", longcode: "" },
  { name: "EBSU Microfinance Bank", code: "50922", slug: "ebsu-microfinance-bank-ng", longcode: "090427" },
  { name: "Ecobank Nigeria", code: "050", slug: "ecobank-nigeria", longcode: "050150010" },
  { name: "Ekimogun MFB", code: "50263", slug: "ekimogun-mfb-ng", longcode: "" },
  { name: "Ekondo Microfinance Bank", code: "098", slug: "ekondo-microfinance-bank-ng", longcode: "" },
  { name: "EXCEL FINANCE BANK", code: "090678", slug: "excel-finance-bank-ng", longcode: "090678" },
  { name: "Eyowo", code: "50126", slug: "eyowo", longcode: "" },
  { name: "Fairmoney Microfinance Bank", code: "51318", slug: "fairmoney-microfinance-bank-ng", longcode: "" },
  { name: "Fedeth MFB", code: "50298", slug: "fedeth-mfb-ng", longcode: "090482" },
  { name: "Fidelity Bank", code: "070", slug: "fidelity-bank", longcode: "070150003" },
  { name: "Firmus MFB", code: "51314", slug: "firmus-mfb", longcode: "" },
  { name: "First Bank of Nigeria", code: "011", slug: "first-bank-of-nigeria", longcode: "011151003" },
  { name: "First City Monument Bank", code: "214", slug: "first-city-monument-bank", longcode: "214150018" },
  { name: "FIRST ROYAL MICROFINANCE BANK", code: "090164", slug: "first-royal-microfinance-bank-ng", longcode: "090164" },
  { name: "FIRSTMIDAS MFB", code: "51333", slug: "firstmidas-mfb-ng", longcode: "090575" },
  { name: "FirstTrust Mortgage Bank Nigeria", code: "413", slug: "firsttrust-mortgage-bank-nigeria-ng", longcode: "" },
  { name: "FSDH Merchant Bank Limited", code: "501", slug: "fsdh-merchant-bank-limited", longcode: "" },
  { name: "FUTMINNA MICROFINANCE BANK", code: "832", slug: "futminna-microfinance-bank-ng", longcode: "832" },
  { name: "Garun Mallam MFB", code: "MFB51093", slug: "garun-mallam-mfb-ng", longcode: "MFB51093" },
  { name: "Gateway Mortgage Bank LTD", code: "812", slug: "gateway-mortgage-bank", longcode: "" },
  { name: "Globus Bank", code: "00103", slug: "globus-bank", longcode: "103015001" },
  { name: "Goldman MFB", code: "090574", slug: "goldman-mfb-ng", longcode: "950356" },
  { name: "GoMoney", code: "100022", slug: "gomoney", longcode: "" },
  { name: "GOOD SHEPHERD MICROFINANCE BANK", code: "090664", slug: "good-shepherd-microfinance-bank-ng", longcode: "090664" },
  { name: "Goodnews Microfinance Bank", code: "50739", slug: "goodnews-microfinance-bank-ng", longcode: "" },
  { name: "Greenwich Merchant Bank", code: "562", slug: "greenwich-merchant-bank-ng", longcode: "" },
  { name: "GROOMING MICROFINANCE BANK", code: "51276", slug: "grooming-microfinance-bank-ng", longcode: "51276" },
  { name: "GTI MFB", code: "50368", slug: "gti-mfb-ng", longcode: "090385" },
  { name: "Guaranty Trust Bank", code: "058", slug: "guaranty-trust-bank", longcode: "058152036" },
  { name: "Hackman Microfinance Bank", code: "51251", slug: "hackman-microfinance-bank", longcode: "" },
  { name: "Hasal Microfinance Bank", code: "50383", slug: "hasal-microfinance-bank", longcode: "" },
  { name: "Hayat Trust MFB", code: "51364", slug: "hayat-trust-mfb-ng", longcode: "090777" },
  { name: "HopePSB", code: "120002", slug: "hopepsb-ng", longcode: "120002" },
  { name: "IBANK Microfinance Bank", code: "51211", slug: "IBANK-mfb", longcode: "090115" },
  { name: "IBBU MFB", code: "51279", slug: "ibbu-mfb-ng", longcode: "51279" },
  { name: "Ibile Microfinance Bank", code: "51244", slug: "ibile-mfb", longcode: "" },
  { name: "Ibom Mortgage Bank", code: "90012", slug: "ibom-mortgage-bank-ng", longcode: "070025" },
  { name: "Ikoyi Osun MFB", code: "50439", slug: "ikoyi-osun-mfb", longcode: "" },
  { name: "Ilaro Poly Microfinance Bank", code: "50442", slug: "ilaro-poly-microfinance-bank-ng", longcode: "" },
  { name: "Imowo MFB", code: "50453", slug: "imowo-mfb-ng", longcode: "50453" },
  { name: "IMPERIAL HOMES MORTGAGE BANK", code: "415", slug: "imperial-homes-mortage-bank-ng", longcode: "100024" },
  { name: "INDULGE MFB", code: "51392", slug: "indulge-mfb-ng", longcode: "090772" },
  { name: "Infinity MFB", code: "50457", slug: "infinity-mfb", longcode: "" },
  { name: "Infinity trust Mortgage Bank", code: "070016", slug: "infinity-trust-mortgage-bank-ng", longcode: "070016" },
  { name: "ISUA MFB", code: "090701", slug: "isua-mfb-ng", longcode: "090701" },
  { name: "Jaiz Bank", code: "301", slug: "jaiz-bank", longcode: "301080020" },
  { name: "Kadpoly MFB", code: "50502", slug: "kadpoly-mfb", longcode: "" },
  { name: "KANOPOLY MFB", code: "51308", slug: "kanopoly-mfb-ng", longcode: "090592" },
  { name: "Kayvee Microfinance Bank", code: "5129", slug: "kayvee-microfinance-bank-ng", longcode: "090554" },
  { name: "Keystone Bank", code: "082", slug: "keystone-bank", longcode: "082150017" },
  { name: "Kolomoni MFB", code: "899", slug: "kolomoni-mfb-ng", longcode: "090480" },
  { name: "KONGAPAY", code: "100025", slug: "kongapay-tech-ltd", longcode: "100025" },
  { name: "Kredi Money MFB LTD", code: "50200", slug: "kredi-money-mfb", longcode: "" },
  { name: "Kuda Bank", code: "50211", slug: "kuda-bank", longcode: "" },
  { name: "Lagos Building Investment Company Plc.", code: "90052", slug: "lbic-plc", longcode: "" },
  { name: "Letshego Microfinance Bank", code: "090420", slug: "letshego-microfinance-bank", longcode: "090420" },
  { name: "Links MFB", code: "50549", slug: "links-mfb", longcode: "" },
  { name: "Living Trust Mortgage Bank", code: "031", slug: "living-trust-mortgage-bank", longcode: "" },
  { name: "LOMA MFB", code: "50491", slug: "loma-mfb-ng", longcode: "090620" },
  { name: "Lotus Bank", code: "303", slug: "lotus-bank", longcode: "" },
  { name: "Maal MFB", code: "51444", slug: "maal-mfb-ng", longcode: "" },
  { name: "MAINSTREET MICROFINANCE BANK", code: "090171", slug: "mainstreet-microfinance-bank-ng", longcode: "090171" },
  { name: "Mayfair MFB", code: "50563", slug: "mayfair-mfb", longcode: "" },
  { name: "Mint MFB", code: "50304", slug: "mint-mfb", longcode: "" },
  { name: "MINT-FINEX MFB", code: "09", slug: "mint-finex-mfb-ng", longcode: "090281" },
  { name: "Money Master PSB", code: "946", slug: "money-master-psb-ng", longcode: "" },
  { name: "Moniepoint MFB", code: "50515", slug: "moniepoint-mfb-ng", longcode: null },
  { name: "MTN Momo PSB", code: "120003", slug: "mtn-momo-psb-ng", longcode: "120003" },
  { name: "MUTUAL BENEFITS MICROFINANCE BANK", code: "090190", slug: "mutual-benefits-microfinance-bank-ng", longcode: "090190" },
  { name: "NDCC MICROFINANCE BANK", code: "090679", slug: "ndcc-microfinance-bank-ng", longcode: "090679" },
  { name: "NET MICROFINANCE BANK", code: "51361", slug: "net-microfinance-bank-ng", longcode: "51361" },
  { name: "Nigerian Navy Microfinance Bank Limited", code: "51142", slug: "nigerian-navy-microfinance-bank-limited-ng", longcode: "090263" },
  { name: "Nombank MFB", code: "50072", slug: "nombank-mfb-ng", longcode: "090645" },
  { name: "NOVA BANK", code: "561", slug: "nova-bank-ng", longcode: "060003" },
  { name: "Novus MFB", code: "51371", slug: "novus-mfb-ng", longcode: "090734" },
  { name: "NPF MICROFINANCE BANK", code: "50629", slug: "npf-microfinance-bank-ng", longcode: "50629" },
  { name: "NSUK MICROFINANCE BANK", code: "51261", slug: "nsuk-microfinanace-bank-ng", longcode: "090491" },
  { name: "Olabisi Onabanjo University Microfinance Bank", code: "50689", slug: "olabisi-onabanjo-university-microfinance-bank-ng", longcode: "090272" },
  { name: "OLUCHUKWU MICROFINANCE BANK LTD", code: "50697", slug: "oluchukwu-microfinance-bank-ltd-ng", longcode: "50697" },
  { name: "OPay Digital Services Limited (OPay)", code: "999992", slug: "paycom", longcode: "" },
  { name: "Optimus Bank Limited", code: "107", slug: "optimus-bank-ltd", longcode: "00107" },
  { name: "Paga", code: "100002", slug: "paga", longcode: "" },
  { name: "PalmPaystack-Titan", code: "100039", slug: "titan-paystack", longcode: "" },
  { name: "Peace Microfinance Bank", code: "50743", slug: "peace-microfinance-bank-ng", longcode: "50743" },
  { name: "PECANTRUST MICROFINANCE BANK LIMITED", code: "51226", slug: "pecantrust-microfinance-bank-limited-ng", longcode: "51226" },
  { name: "Personal Trust MFB", code: "51146", slug: "personal-trust-mfb-ng", longcode: "" },
  { name: "Petra Microfinance Bank Plc", code: "50746", slug: "petra-microfinance-bank-plc", longcode: "" },
  { name: "Pettysave MFB", code: "MFB51452", slug: "pettysave-mfb-ng", longcode: "090768" },
  { name: "PFI FINANCE COMPANY LIMITED", code: "050021", slug: "pfi-finance-company-limited-ng", longcode: "050021" },
  { name: "Platinum Mortgage Bank", code: "268", slug: "platinum-mortgage-bank-ng", longcode: null },
  { name: "Pocket App", code: "00716", slug: "pocket", longcode: "00716" },
  { name: "Polaris Bank", code: "076", slug: "polaris-bank", longcode: "076151006" },
  { name: "Polyunwana MFB", code: "50864", slug: "polyunwana-mfb-ng", longcode: null },
  { name: "PremiumTrust Bank", code: "105", slug: "premiumtrust-bank-ng", longcode: "000031" },
  { name: "Prospa Capital Microfinance Bank", code: "50739", slug: "prospa-capital-microfinance-bank-ng", longcode: "50739" },
  { name: "PROSPERIS FINANCE LIMITED", code: "050023", slug: "prosperis-finance-limited-ng", longcode: "050023" },
  { name: "Providus Bank", code: "101", slug: "providus-bank", longcode: "" },
  { name: "QuickFund MFB", code: "51293", slug: "quickfund-mfb", longcode: "" },
  { name: "Rand Merchant Bank", code: "502", slug: "rand-merchant-bank", longcode: "" },
  { name: "RANDALPHA MICROFINANCE BANK", code: "090496", slug: "randalpha-microfinance-bank-ng", longcode: "090496" },
  { name: "Refuge Mortgage Bank", code: "90067", slug: "refuge-mortgage-bank", longcode: "" },
  { name: "REHOBOTH MICROFINANCE BANK", code: "50761", slug: "rehoboth-microfinance-bank-ng", longcode: "090463" },
  { name: "Rephidim Microfinance Bank", code: "50994", slug: "rephidim", longcode: "221151615" },
  { name: "Rigo Microfinance Bank Limited", code: "51286", slug: "rigo-microfinance-bank-limited-ng", longcode: "51286" },
  { name: "ROCKSHIELD MICROFINANCE BANK", code: "50767", slug: "rockshield-microfinance-bank-ng", longcode: "" },
  { name: "Rubies MFB", code: "125", slug: "rubies-mfb", longcode: "" },
  { name: "Safe Haven MFB", code: "51113", slug: "safe-haven-mfb-ng", longcode: "51113" },
  { name: "SAGE GREY FINANCE LIMITED", code: "40165", slug: "sage-grey-finance-limited-ng", longcode: null },
  { name: "Shield MFB", code: "50582", slug: "shield-mfb-ng", longcode: "" },
  { name: "Signature Bank Ltd", code: "106", slug: "signature-bank-ltd-ng", longcode: "000034" },
  { name: "Solid Allianze MFB", code: "51062", slug: "solid-allianze-mfb", longcode: "" },
  { name: "Solid Rock MFB", code: "50800", slug: "solid-rock-mfb", longcode: "" },
  { name: "Sparkle Microfinance Bank", code: "51310", slug: "sparkle-microfinance-bank", longcode: "" },
  { name: "Springfield Microfinance Bank", code: "51429", slug: "springfield-microfinance-bank-ng", longcode: "090806" },
  { name: "Stanbic IBTC Bank", code: "221", slug: "stanbic-ibtc-bank", longcode: "221159522" },
  { name: "Standard Chartered Bank", code: "068", slug: "standard-chartered-bank", longcode: "068150015" },
  { name: "STANFORD MICROFINANCE BANK", code: "090162", slug: "stanford-microfinance-bank-ng", longcode: "090162" },
  { name: "STATESIDE MICROFINANCE BANK", code: "50809", slug: "stateside-microfinance-bank-ng", longcode: "50809" },
  { name: "STB Mortgage Bank", code: "070022", slug: "stb-mortgage-bank-ng", longcode: "070022" },
  { name: "Stellas MFB", code: "51253", slug: "stellas-mfb", longcode: "" },
  { name: "Sterling Bank", code: "232", slug: "sterling-bank", longcode: "232150016" },
  { name: "Summit Bank", code: "00305", slug: "summit-bank-ng", longcode: "080003" },
  { name: "Suntrust Bank", code: "100", slug: "suntrust-bank", longcode: "" },
  { name: "Supreme MFB", code: "50968", slug: "supreme-mfb-ng", longcode: "" },
  { name: "TAJ Bank", code: "302", slug: "taj-bank", longcode: "" },
  { name: "Tangerine Money", code: "51269", slug: "tangerine-money", longcode: "" },
  { name: "TENN", code: "51403", slug: "tenn-ng", longcode: "090716" },
  { name: "Think Finance Microfinance Bank", code: "677", slug: "think-finance-microfinance-bank-ng", longcode: "090373" },
  { name: "Titan Bank", code: "102", slug: "titan-bank", longcode: "" },
  { name: "TransPay MFB", code: "090708", slug: "transpay-mfb-ng", longcode: "090708" },
  { name: "TRUSTBANC J6 MICROFINANCE BANK", code: "51118", slug: "trustbanc-j6-microfinance-bank-ng", longcode: "090123" },
  { name: "U&C Microfinance Bank Ltd", code: "50840", slug: "uc-microfinance-bank-ltd-u-and-c-mfb-ng", longcode: "50840" },
  { name: "UCEE MFB", code: "090706", slug: "ucee-mfb-ng", longcode: "090706" },
  { name: "Uhuru MFB", code: "51322", slug: "uhuru-mfb-ng", longcode: "" },
  { name: "Ultraviolet Microfinance Bank", code: "51080", slug: "ultraviolet-microfinance-bank-ng", longcode: "090781" },
  { name: "Unaab Microfinance Bank Limited", code: "50870", slug: "unaab-microfinance-bank-limited-ng", longcode: "" },
  { name: "UNIABUJA MFB", code: "51447", slug: "uniabuja-mfb", longcode: "MFB51447" },
  { name: "Unical MFB", code: "50871", slug: "unical-mfb", longcode: "" },
  { name: "Unilag Microfinance Bank", code: "51316", slug: "unilag-microfinance-bank-ng", longcode: "" },
  { name: "UNIMAID MICROFINANCE BANK", code: "50875", slug: "unimaid-microfinance-bank-ng", longcode: "090464" },
  { name: "Union Bank of Nigeria", code: "032", slug: "union-bank-of-nigeria", longcode: "032080474" },
  { name: "United Bank For Africa", code: "033", slug: "united-bank-for-africa", longcode: "033153513" },
  { name: "Unity Bank", code: "215", slug: "unity-bank", longcode: "215154097" },
  { name: "Uzondu Microfinance Bank Awka Anambra State", code: "50894", slug: "uzondu-microfinance-bank-awka-anambra-state-ng", longcode: "50894" },
  { name: "Vale Finance Limited", code: "050020", slug: "vale-finance", longcode: "" },
  { name: "VFD Microfinance Bank Limited", code: "566", slug: "vfd", longcode: "" },
  { name: "Waya Microfinance Bank", code: "51355", slug: "waya-microfinance-bank-ng", longcode: "51355" },
  { name: "Wema Bank", code: "035", slug: "wema-bank", longcode: "035150103" },
  { name: "Weston Charis MFB", code: "51386", slug: "weston-charis-mfb-ng", longcode: "090741" },
  { name: "Xpress Wallet", code: "100040", slug: "xpress-wallet-ng", longcode: "100040" },
  { name: "Yes MFB", code: "594", slug: "yes-mfb-ng", longcode: "090142" },
  { name: "Zap", code: "00zap", slug: "zap", longcode: "00zap" },
  { name: "Zenith Bank", code: "057", slug: "zenith-bank", longcode: "057150013" },
  { name: "Zitra MFB", code: "51373", slug: "zitra-mfb-ng", longcode: "090718" }
];
    