// banks.js
// export const NIGERIAN_BANKS = [
//   {
//     id: 302,
//     name: "9mobile 9Payment Service Bank",
//     slug: "9mobile-9payment-service-bank-ng",
//     code: "120001",
//     longcode: "120001",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-05-31T06:50:27.000Z",
//     updatedAt: "2022-06-23T09:33:55.000Z"
//   },
//   {
//     id: 174,
//     name: "Abbey Mortgage Bank",
//     slug: "abbey-mortgage-bank-ng",
//     code: "404",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2020-12-07T16:19:09.000Z",
//     updatedAt: "2023-09-14T13:02:38.000Z"
//   },
//   {
//     id: 188,
//     name: "Above Only MFB",
//     slug: "above-only-mfb",
//     code: "51204",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2021-10-13T20:35:17.000Z",
//     updatedAt: "2021-10-13T20:35:17.000Z"
//   },
//   {
//     id: 627,
//     name: "Abulesoro MFB",
//     slug: "abulesoro-mfb-ng",
//     code: "51312",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-08-31T08:26:20.000Z",
//     updatedAt: "2022-08-31T08:26:20.000Z"
//   },
//   {
//     id: 1,
//     name: "Access Bank",
//     slug: "access-bank",
//     code: "044",
//     longcode: "044150149",
//     gateway: "emandate",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: true,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2016-07-14T10:04:29.000Z",
//     updatedAt: "2020-02-18T08:06:44.000Z"
//   },
//   {
//     id: 3,
//     name: "Access Bank (Diamond)",
//     slug: "access-bank-diamond",
//     code: "063",
//     longcode: "063150162",
//     gateway: "emandate",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2016-07-14T10:04:29.000Z",
//     updatedAt: "2020-02-18T08:06:48.000Z"
//   },
//   {
//     id: 495,
//     name: "Accion Microfinance Bank",
//     slug: "accion-microfinance-bank-ng",
//     code: "602",
//     longcode: "",
//     gateway: "emandate",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-07-28T14:22:56.000Z",
//     updatedAt: "2022-09-19T07:48:37.000Z"
//   },
//   {
//     id: 687,
//     name: "Aella MFB",
//     slug: "aella-mfb-ng",
//     code: "50315",
//     longcode: "50315",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-03-09T08:11:06.000Z",
//     updatedAt: "2024-07-30T10:51:33.000Z"
//   },
//   {
//     id: 780,
//     name: "AG Mortgage Bank",
//     slug: "ag-mortgage-bank-ng",
//     code: "90077",
//     longcode: "100028",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-06-07T13:28:00.000Z",
//     updatedAt: "2024-06-07T13:28:00.000Z"
//   },
//   {
//     id: 676,
//     name: "Ahmadu Bello University Microfinance Bank",
//     slug: "ahmadu-bello-university-microfinance-bank-ng",
//     code: "50036",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-11-14T13:35:42.000Z",
//     updatedAt: "2022-11-14T13:35:42.000Z"
//   },
//   {
//     id: 300,
//     name: "Airtel Smartcash PSB",
//     slug: "airtel-smartcash-psb-ng",
//     code: "120004",
//     longcode: "120004",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-05-30T14:03:00.000Z",
//     updatedAt: "2022-05-31T06:58:22.000Z"
//   },
//   {
//     id: 698,
//     name: "AKU Microfinance Bank",
//     slug: "aku-mfb",
//     code: "51336",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-05-04T15:12:34.000Z",
//     updatedAt: "2023-05-04T15:12:34.000Z"
//   },
//   {
//     id: 497,
//     name: "Akuchukwu Microfinance Bank Limited",
//     slug: "akuchukwu-microfinance-bank-limited-ng",
//     code: "090561",
//     longcode: "090561",
//     gateway: "emandate",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-07-28T14:22:56.000Z",
//     updatedAt: "2023-11-03T12:09:37.000Z"
//   },
//   {
//     id: 872,
//     name: "Al-Barakah Microfinance Bank",
//     slug: "al-barakah-microfinance-bank-ng",
//     code: "50055",
//     longcode: "090133",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2025-10-17T10:08:10.000Z",
//     updatedAt: "2025-10-17T10:08:10.000Z"
//   },
//   {
//     id: 27,
//     name: "ALAT by WEMA",
//     slug: "alat-by-wema",
//     code: "035A",
//     longcode: "035150103",
//     gateway: "emandate",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2017-11-15T12:21:31.000Z",
//     updatedAt: "2022-05-31T15:54:34.000Z"
//   },
//   {
//     id: 857,
//     name: "Alpha Morgan Bank",
//     slug: "alpha-morgan",
//     code: "108",
//     longcode: "000041",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2025-06-16T10:33:05.000Z",
//     updatedAt: "2025-06-16T10:33:05.000Z"
//   },
//   {
//     id: 790,
//     name: "Alternative bank",
//     slug: "the-alternative-bank-ng",
//     code: "000304",
//     longcode: "000304",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-08-06T12:31:06.000Z",
//     updatedAt: "2025-02-19T13:05:14.000Z"
//   },
//   {
//     id: 707,
//     name: "Amegy Microfinance Bank",
//     slug: "amegy-microfinance-bank-ng",
//     code: "090629",
//     longcode: "090629",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-07-20T09:52:18.000Z",
//     updatedAt: "2023-07-20T09:52:18.000Z"
//   },
//   {
//     id: 179,
//     name: "Amju Unique MFB",
//     slug: "amju-unique-mfb",
//     code: "50926",
//     longcode: "511080896",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2021-07-07T13:45:57.000Z",
//     updatedAt: "2021-07-07T13:45:57.000Z"
//   },
//   {
//     id: 614,
//     name: "Aramoko MFB",
//     slug: "aramoko-mfb",
//     code: "50083",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-08-10T09:48:24.000Z",
//     updatedAt: "2022-08-10T09:48:24.000Z"
//   },
//   {
//     id: 63,
//     name: "ASO Savings and Loans",
//     slug: "asosavings",
//     code: "401",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2018-09-23T05:52:38.000Z",
//     updatedAt: "2019-01-30T09:38:57.000Z"
//   },
//   {
//     id: 793,
//     name: "Assets Microfinance Bank",
//     slug: "assets-microfinance-bank-ng",
//     code: "50092",
//     longcode: "50092",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-08-21T11:36:11.000Z",
//     updatedAt: "2024-08-21T11:36:11.000Z"
//   },
//   {
//     id: 297,
//     name: "Astrapolaris MFB LTD",
//     slug: "astrapolaris-mfb",
//     code: "MFB50094",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-05-25T10:46:17.000Z",
//     updatedAt: "2022-05-25T10:46:17.000Z"
//   },
//   {
//     id: 759,
//     name: "AVUENEGBE MICROFINANCE BANK",
//     slug: "avuenegbe-microfinance-bank-ng",
//     code: "090478",
//     longcode: "090478",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-12-30T06:19:20.000Z",
//     updatedAt: "2023-12-30T06:19:20.000Z"
//   },
//   {
//     id: 778,
//     name: "AWACASH MICROFINANCE BANK",
//     slug: "awacash-microfinance-bank-ng",
//     code: "51351",
//     longcode: "51351",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: " Abuja",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-05-20T10:27:56.000Z",
//     updatedAt: "2024-05-20T10:27:56.000Z"
//   },
//   {
//     id: 796,
//     name: "AZTEC MICROFINANCE BANK LIMITED",
//     slug: "aztec-microfinance-bank-limited-ng",
//     code: "51337",
//     longcode: "090540",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-08-28T14:36:20.000Z",
//     updatedAt: "2024-08-28T14:36:20.000Z"
//   },
//   {
//     id: 181,
//     name: "Bainescredit MFB",
//     slug: "bainescredit-mfb",
//     code: "51229",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2021-07-12T14:41:18.000Z",
//     updatedAt: "2021-07-12T14:41:18.000Z"
//   },
//   {
//     id: 686,
//     name: "Banc Corp Microfinance Bank",
//     slug: "banc-corp-microfinance-bank-ng",
//     code: "50117",
//     longcode: "50117",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-03-06T15:39:58.000Z",
//     updatedAt: "2023-03-06T15:39:58.000Z"
//   },
//   {
//     id: 832,
//     name: "BANKIT MICROFINANCE BANK LTD",
//     slug: "bankit-microfinance-bank-ltd-ng",
//     code: "50572",
//     longcode: "090275",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2025-04-02T13:12:36.000Z",
//     updatedAt: "2025-04-02T13:12:36.000Z"
//   },
//   {
//     id: 689,
//     name: "BANKLY MFB",
//     slug: "ampersand-microfinance-bank-ng",
//     code: "51341",
//     longcode: "",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-03-23T11:11:40.000Z",
//     updatedAt: "2024-10-22T07:32:28.000Z"
//   },
//   {
//     id: 777,
//     name: "Baobab Microfinance Bank",
//     slug: "baobab-microfinance-bank-ng",
//     code: "MFB50992",
//     longcode: "MFB50992",
//     gateway: "null",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-05-08T09:06:52.000Z",
//     updatedAt: "2024-05-08T09:06:52.000Z"
//   },
//   {
//     id: 783,
//     name: "BellBank Microfinance Bank",
//     slug: "bellbank-microfinance-bank-ng",
//     code: "51100",
//     longcode: "51100",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-07-02T11:56:37.000Z",
//     updatedAt: "2024-07-02T11:56:37.000Z"
//   },
//   {
//     id: 589,
//     name: "Benysta Microfinance Bank Limited",
//     slug: "benysta-microfinance-bank-limited",
//     code: "51267",
//     longcode: "51267",
//     gateway: "emandate",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-07-28T14:22:56.000Z",
//     updatedAt: "2024-07-04T11:12:27.000Z"
//   },
//   {
//     id: 771,
//     name: "Beststar Microfinance Bank",
//     slug: "beststar-microfinance-bank-ng",
//     code: "50123",
//     longcode: "090615",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-01-26T08:55:14.000Z",
//     updatedAt: "2024-01-26T08:55:14.000Z"
//   },
//   {
//     id: 816,
//     name: "BOLD MFB",
//     slug: "bold-mfb-ng",
//     code: "50725",
//     longcode: "090753",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-12-20T11:31:23.000Z",
//     updatedAt: "2024-12-20T14:06:12.000Z"
//   },
//   {
//     id: 815,
//     name: "Bosak Microfinance Bank",
//     slug: "bosak-microfinance-bank-ng",
//     code: "650",
//     longcode: "650",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-12-16T12:21:26.000Z",
//     updatedAt: "2024-12-16T12:21:26.000Z"
//   },
//   {
//     id: 108,
//     name: "Bowen Microfinance Bank",
//     slug: "bowen-microfinance-bank",
//     code: "50931",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2020-02-11T15:38:57.000Z",
//     updatedAt: "2020-02-11T15:38:57.000Z"
//   },
//   {
//     id: 697,
//     name: "Branch International Finance Company Limited",
//     slug: "branch",
//     code: "FC40163",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-05-04T09:49:07.000Z",
//     updatedAt: "2024-10-23T10:37:58.000Z"
//   },
//   {
//     id: 867,
//     name: "Brent Mortgage bank",
//     slug: "brent-mortgage-bank-ng",
//     code: "90070",
//     longcode: "070015",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2025-09-17T06:54:19.000Z",
//     updatedAt: "2025-09-17T06:54:19.000Z"
//   },
//   {
//     id: 817,
//     name: "BuyPower MFB",
//     slug: "buypower-mfb-ng",
//     code: "50645",
//     longcode: "50645",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2025-01-13T12:40:37.000Z",
//     updatedAt: "2025-01-13T15:31:54.000Z"
//   },
//   {
//     id: 82,
//     name: "Carbon",
//     slug: "carbon",
//     code: "565",
//     longcode: "",
//     gateway: "digitalbankmandate",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2020-06-16T08:15:31.000Z",
//     updatedAt: "2025-03-10T13:42:25.000Z"
//   },
//   {
//     id: 781,
//     name: "Cashbridge Microfinance Bank Limited",
//     slug: "cashbridge-mfb-ng",
//     code: "51353",
//     longcode: "51353",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-06-27T13:01:40.000Z",
//     updatedAt: "2024-06-27T13:01:40.000Z"
//   },
//   {
//     id: 692,
//     name: "CASHCONNECT MFB",
//     slug: "cashconnect-mfb-ng",
//     code: "865",
//     longcode: "865",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-04-05T14:29:19.000Z",
//     updatedAt: "2023-04-05T14:29:19.000Z"
//   },
//   {
//     id: 74,
//     name: "CEMCS Microfinance Bank",
//     slug: "cemcs-microfinance-bank",
//     code: "50823",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2020-03-23T15:06:13.000Z",
//     updatedAt: "2020-03-23T15:06:28.000Z"
//   },
//   {
//     id: 284,
//     name: "Chanelle Microfinance Bank Limited",
//     slug: "chanelle-microfinance-bank-limited-ng",
//     code: "50171",
//     longcode: "50171",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-02-10T13:28:38.000Z",
//     updatedAt: "2022-02-10T13:28:38.000Z"
//   },
//   {
//     id: 704,
//     name: "Chikum Microfinance bank",
//     slug: "chikum-microfinance-bank-ng",
//     code: "312",
//     longcode: "null",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-07-03T11:21:07.000Z",
//     updatedAt: "2023-07-03T11:21:07.000Z"
//   },
//   {
//     id: 2,
//     name: "Citibank Nigeria",
//     slug: "citibank-nigeria",
//     code: "023",
//     longcode: "023150005",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: true,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2016-07-14T10:04:29.000Z",
//     updatedAt: "2020-02-18T20:24:02.000Z"
//   },
//   {
//     id: 755,
//     name: "CITYCODE MORTAGE BANK",
//     slug: "citycode-mortage-bank-ng",
//     code: "070027",
//     longcode: "070027",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-12-30T06:16:39.000Z",
//     updatedAt: "2023-12-30T06:16:39.000Z"
//   },
//   {
//     id: 691,
//     name: "Consumer Microfinance Bank",
//     slug: "consumer-microfinance-bank-ng",
//     code: "50910",
//     longcode: "50910",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-03-28T06:18:02.000Z",
//     updatedAt: "2023-03-28T06:18:02.000Z"
//   },
//   {
//     id: 283,
//     name: "Corestep MFB",
//     slug: "corestep-mfb",
//     code: "50204",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-02-09T14:33:06.000Z",
//     updatedAt: "2022-02-09T14:33:06.000Z"
//   },
//   {
//     id: 173,
//     name: "Coronation Merchant Bank",
//     slug: "coronation-merchant-bank-ng",
//     code: "559",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2020-11-24T10:25:07.000Z",
//     updatedAt: "2023-05-04T06:49:08.000Z"
//   },
//   {
//     id: 694,
//     name: "County Finance Limited",
//     slug: "county-finance-limited",
//     code: "FC40128",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-04-26T14:24:23.000Z",
//     updatedAt: "2023-04-26T14:24:23.000Z"
//   },
//   {
//     id: 829,
//     name: "Credit Direct Limited",
//     slug: "credit-direct-limited-ng",
//     code: "40119",
//     longcode: "110049",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2025-03-15T18:14:25.000Z",
//     updatedAt: "2025-03-15T18:14:25.000Z"
//   },
//   {
//     id: 366,
//     name: "Crescent MFB",
//     slug: "crescent-mfb",
//     code: "51297",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-07-18T12:39:03.000Z",
//     updatedAt: "2022-07-18T12:39:03.000Z"
//   },
//   {
//     id: 634,
//     name: "Crust Microfinance Bank",
//     slug: "crust-microfinance-bank-ng",
//     code: "090560",
//     longcode: "",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-09-22T09:14:25.000Z",
//     updatedAt: "2023-12-12T15:46:28.000Z"
//   },
//   {
//     id: 820,
//     name: "CRUTECH MICROFINANCE BANK LTD",
//     slug: "crutech-microfinance-bank-ltd-ng",
//     code: "50216",
//     longcode: "090414",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2025-01-24T12:05:13.000Z",
//     updatedAt: "2025-04-15T15:27:51.000Z"
//   },
//   {
//     id: 865,
//     name: "Dash Microfinance Bank",
//     slug: "dash-microfinance-bank-ng",
//     code: "51368",
//     longcode: "090845",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2025-09-12T15:03:26.000Z",
//     updatedAt: "2025-09-12T15:03:26.000Z"
//   },
//   {
//     id: 738,
//     name: "Davenport MICROFINANCE BANK",
//     slug: "davenport-microfinance-bank-ng",
//     code: "51334",
//     longcode: "51334",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-11-20T13:30:56.000Z",
//     updatedAt: "2023-11-20T13:30:56.000Z"
//   },
//   {
//     id: 860,
//     name: "Dillon Microfinance Bank",
//     slug: "dillon-microfinance-bank-ng",
//     code: "51450",
//     longcode: "09828",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2025-07-31T15:52:51.000Z",
//     updatedAt: "2025-07-31T15:52:51.000Z"
//   },
//   {
//     id: 637,
//     name: "Dot Microfinance Bank",
//     slug: "dot-microfinance-bank-ng",
//     code: "50162",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-11-03T14:39:09.000Z",
//     updatedAt: "2022-11-03T14:39:09.000Z"
//   },
//   {
//     id: 821,
//     name: "EBSU Microfinance Bank",
//     slug: "ebsu-microfinance-bank-ng",
//     code: "50922",
//     longcode: "090427",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2025-02-10T13:06:52.000Z",
//     updatedAt: "2025-02-10T13:06:52.000Z"
//   },
//   {
//     id: 4,
//     name: "Ecobank Nigeria",
//     slug: "ecobank-nigeria",
//     code: "050",
//     longcode: "050150010",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: true,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2016-07-14T10:04:29.000Z",
//     updatedAt: "2020-02-18T20:23:53.000Z"
//   },
//   {
//     id: 628,
//     name: "Ekimogun MFB",
//     slug: "ekimogun-mfb-ng",
//     code: "50263",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-08-31T08:26:39.000Z",
//     updatedAt: "2022-08-31T08:26:39.000Z"
//   },
//   {
//     id: 64,
//     name: "Ekondo Microfinance Bank",
//     slug: "ekondo-microfinance-bank-ng",
//     code: "098",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2018-09-23T05:55:06.000Z",
//     updatedAt: "2022-09-21T15:09:51.000Z"
//   },
//   {
//     id: 761,
//     name: "EXCEL FINANCE BANK",
//     slug: "excel-finance-bank-ng",
//     code: "090678",
//     longcode: "090678",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-12-30T06:19:49.000Z",
//     updatedAt: "2023-12-30T06:19:49.000Z"
//   },
//   {
//     id: 167,
//     name: "Eyowo",
//     slug: "eyowo",
//     code: "50126",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2020-09-07T13:52:22.000Z",
//     updatedAt: "2020-11-24T10:03:21.000Z"
//   },
//   {
//     id: 677,
//     name: "Fairmoney Microfinance Bank",
//     slug: "fairmoney-microfinance-bank-ng",
//     code: "51318",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-11-15T12:33:47.000Z",
//     updatedAt: "2022-11-15T12:37:44.000Z"
//   },
//   {
//     id: 767,
//     name: "Fedeth MFB",
//     slug: "fedeth-mfb-ng",
//     code: "50298",
//     longcode: "090482",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-01-04T14:09:56.000Z",
//     updatedAt: "2024-01-04T14:09:56.000Z"
//   },
//   {
//     id: 6,
//     name: "Fidelity Bank",
//     slug: "fidelity-bank",
//     code: "070",
//     longcode: "070150003",
//     gateway: "emandate",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: true,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2016-07-14T10:04:29.000Z",
//     updatedAt: "2021-08-27T09:15:29.000Z"
//   },
//   {
//     id: 177,
//     name: "Firmus MFB",
//     slug: "firmus-mfb",
//     code: "51314",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2021-06-01T15:33:26.000Z",
//     updatedAt: "2021-06-01T15:33:26.000Z"
//   },
//   {
//     id: 7,
//     name: "First Bank of Nigeria",
//     slug: "first-bank-of-nigeria",
//     code: "011",
//     longcode: "011151003",
//     gateway: "ibank",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: true,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2016-07-14T10:04:29.000Z",
//     updatedAt: "2021-03-25T14:22:52.000Z"
//   },
//   {
//     id: 8,
//     name: "First City Monument Bank",
//     slug: "first-city-monument-bank",
//     code: "214",
//     longcode: "214150018",
//     gateway: "emandate",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: true,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2016-07-14T10:04:29.000Z",
//     updatedAt: "2020-02-18T08:06:46.000Z"
//   },
//   {
//     id: 757,
//     name: "FIRST ROYAL MICROFINANCE BANK",
//     slug: "first-royal-microfinance-bank-ng",
//     code: "090164",
//     longcode: "090164",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-12-30T06:18:48.000Z",
//     updatedAt: "2023-12-30T06:18:48.000Z"
//   },
//   {
//     id: 812,
//     name: "FIRSTMIDAS MFB",
//     slug: "firstmidas-mfb-ng",
//     code: "51333",
//     longcode: "090575",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-12-04T15:04:19.000Z",
//     updatedAt: "2024-12-04T15:04:19.000Z"
//   },
//   {
//     id: 682,
//     name: "FirstTrust Mortgage Bank Nigeria",
//     slug: "firsttrust-mortgage-bank-nigeria-ng",
//     code: "413",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-02-17T12:12:37.000Z",
//     updatedAt: "2023-06-15T16:21:12.000Z"
//   },
//   {
//     id: 112,
//     name: "FSDH Merchant Bank Limited",
//     slug: "fsdh-merchant-bank-limited",
//     code: "501",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2020-08-20T09:37:04.000Z",
//     updatedAt: "2020-11-24T10:03:22.000Z"
//   },
//   {
//     id: 716,
//     name: "FUTMINNA MICROFINANCE BANK",
//     slug: "futminna-microfinance-bank-ng",
//     code: "832",
//     longcode: "832",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-10-11T13:24:17.000Z",
//     updatedAt: "2023-10-11T13:24:17.000Z"
//   },
//   {
//     id: 794,
//     name: "Garun Mallam MFB",
//     slug: "garun-mallam-mfb-ng",
//     code: "MFB51093",
//     longcode: "MFB51093",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-08-23T09:24:06.000Z",
//     updatedAt: "2024-08-23T09:24:06.000Z"
//   },
//   {
//     id: 287,
//     name: "Gateway Mortgage Bank LTD",
//     slug: "gateway-mortgage-bank",
//     code: "812",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-02-24T06:04:39.000Z",
//     updatedAt: "2022-02-24T06:04:39.000Z"
//   },
//   {
//     id: 70,
//     name: "Globus Bank",
//     slug: "globus-bank",
//     code: "00103",
//     longcode: "103015001",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: true,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2020-02-11T15:38:57.000Z",
//     updatedAt: "2020-02-11T15:38:57.000Z"
//   },
//   {
//     id: 769,
//     name: "Goldman MFB",
//     slug: "goldman-mfb-ng",
//     code: "090574",
//     longcode: "950356",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-01-12T10:05:20.000Z",
//     updatedAt: "2024-01-12T10:05:20.000Z"
//   },
//   {
//     id: 183,
//     name: "GoMoney",
//     slug: "gomoney",
//     code: "100022",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2021-08-04T11:49:46.000Z",
//     updatedAt: "2021-11-12T13:32:14.000Z"
//   },
//   {
//     id: 756,
//     name: "GOOD SHEPHERD MICROFINANCE BANK",
//     slug: "good-shepherd-microfinance-bank-ng",
//     code: "090664",
//     longcode: "090664",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-12-30T06:16:56.000Z",
//     updatedAt: "2023-12-30T06:16:56.000Z"
//   },
//   {
//     id: 635,
//     name: "Goodnews Microfinance Bank",
//     slug: "goodnews-microfinance-bank-ng",
//     code: "50739",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-09-29T09:14:18.000Z",
//     updatedAt: "2022-10-18T14:59:07.000Z"
//   },
//   {
//     id: 633,
//     name: "Greenwich Merchant Bank",
//     slug: "greenwich-merchant-bank-ng",
//     code: "562",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-09-16T15:23:58.000Z",
//     updatedAt: "2022-09-16T15:23:58.000Z"
//   },
//   {
//     id: 789,
//     name: "GROOMING MICROFINANCE BANK",
//     slug: "grooming-microfinance-bank-ng",
//     code: "51276",
//     longcode: "51276",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-08-06T10:52:30.000Z",
//     updatedAt: "2024-08-06T10:52:30.000Z"
//   },
//   {
//     id: 824,
//     name: "GTI MFB",
//     slug: "gti-mfb-ng",
//     code: "50368",
//     longcode: "090385",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2025-02-18T09:16:52.000Z",
//     updatedAt: "2025-02-18T09:16:52.000Z"
//   },
//   {
//     id: 9,
//     name: "Guaranty Trust Bank",
//     slug: "guaranty-trust-bank",
//     code: "058",
//     longcode: "058152036",
//     gateway: "ibank",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: true,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//    塑造: "2016-07-14T10:04:29.000Z",
//     updatedAt: "2024-11-14T12:30:43.000Z"
//   },
//   {
//     id: 111,
//     name: "Hackman Microfinance Bank",
//     slug: "hackman-microfinance-bank",
//     code: "51251",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2020-08-20T09:32:48.000Z",
//     updatedAt: "2020-11-24T10:03:24.000Z"
//   },
//   {
//     id: 81,
//     name: "Hasal Microfinance Bank",
//     slug: "hasal-microfinance-bank",
//     code: "50383",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2020-02-11T15:38:57.000Z",
//     updatedAt: "2020-02-11T15:38:57.000Z"
//   },
//   {
//     id: 301,
//     name: "HopePSB",
//     slug: "hopepsb-ng",
//     code: "120002",
//     longcode: "120002",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-05-30T14:03:18.000Z",
//     updatedAt: "2022-05-30T14:03:18.000Z"
//   },
//   {
//     id: 75,
//     name: "IBANK Microfinance Bank",
//     slug: "IBANK-mfb",
//     code: "51211",
//     longcode: "090115",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2020-04-03T09:34:35.000Z",
//     updatedAt: "2024-07-22T11:59:33.000Z"
//   },
//   {
//     id: 828,
//     name: "IBBU MFB",
//     slug: "ibbu-mfb-ng",
//     code: "51279",
//     longcode: "51279",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2025-03-13T11:07:50.000Z",
//     updatedAt: "2025-03-13T11:07:50.000Z"
//   },
//   {
//     id: 168,
//     name: "Ibile Microfinance Bank",
//     slug: "ibile-mfb",
//     code: "51244",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2020-10-21T10:54:20.000Z",
//     updatedAt: "2020-10-21T10:54:33.000Z"
//   },
//   {
//     id: 859,
//     name: "Ibom Mortgage Bank",
//     slug: "ibom-mortgage-bank-ng",
//     code: "90012",
//     longcode: "070025",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2025-07-31T11:20:09.000Z",
//     updatedAt: "2025-07-31T11:20:09.000Z"
//   },
//   {
//     id: 615,
//     name: "Ikoyi Osun MFB",
//     slug: "ikoyi-osun-mfb",
//     code: "50439",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-08-10T09:48:24.000Z",
//     updatedAt: "2022-08-10T09:48:24.000Z"
//   },
//   {
//     id: 636,
//     name: "Ilaro Poly Microfinance Bank",
//     slug: "ilaro-poly-microfinance-bank-ng",
//     code: "50442",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-10-12T09:15:26.000Z",
//     updatedAt: "2022-10-12T09:15:26.000Z"
//   },
//   {
//     id: 703,
//     name: "Imowo MFB",
//     slug: "imowo-mfb-ng",
//     code: "50453",
//     longcode: "50453",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-06-26T13:50:15.000Z",
//     updatedAt: "2023-06-26T13:50:15.000Z"
//   },
//   {
//     id: 754,
//     name: "IMPERIAL HOMES MORTAGE BANK",
//     slug: "imperial-homes-mortage-bank-ng",
//     code: "415",
//     longcode: "100024",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2023-12-30T05:53:07.000Z",
//     updatedAt: "2024-02-12T15:49:56.000Z"
//   },
//   {
//     id: 858,
//     name: "INDULGE MFB",
//     slug: "indulge-mfb-ng",
//     code: "51392",
//     longcode: "090772",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2025-07-31T08:43:41.000Z",
//     updatedAt: "2025-07-31T08:43:41.000Z"
//   },
//   {
//     id: 172,
//     name: "Infinity MFB",
//     slug: "infinity-mfb",
//     code: "50457",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2020-11-24T10:23:37.000Z",
//     updatedAt: "2020-11-24T10:23:37.000Z"
//   },
//   {
//     id: 822,
//     name: "Infinity trust  Mortgage Bank",
//     slug: "infinity-trust-mortgage-bank-ng",
//     code: "070016",
//     longcode: "070016",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2025-02-11T08:33:01.000Z",
//     updatedAt: "2025-02-11T08:33:01.000Z"
//   },
//   {
//     id: 787,
//     name: "ISUA MFB",
//     slug: "isua-mfb-ng",
//     code: "090701",
//     longcode: "090701",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-07-19T12:38:16.000Z",
//     updatedAt: "2024-07-19T12:38:16.000Z"
//   },
//   {
//     id: 22,
//     name: "Jaiz Bank",
//     slug: "jaiz-bank",
//     code: "301",
//     longcode: "301080020",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2016-10-10T17:26:29.000Z",
//     updatedAt: "2016-10-10T17:26:29.000Z"
//   },
//   {
//     id: 187,
//     name: "Kadpoly MFB",
//     slug: "kadpoly-mfb",
//     code: "50502",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2021-09-27T11:59:42.000Z",
//     updatedAt: "2021-09-27T11:59:42.000Z"
//   },
//   {
//     id: 768,
//     name: "KANOPOLY MFB",
//     slug: "kanopoly-mfb-ng",
//     code: "51308",
//     longcode: "090592",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-01-04T14:20:38.000Z",
//     updatedAt: "2024-01-04T14:20:38.000Z"
//   },
//   {
//     id: 11,
//     name: "Keystone Bank",
//     slug: "keystone-bank",
//     code: "082",
//     longcode: "082150017",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2016-07-14T10:04:29.000Z",
//     updatedAt: "2020-02-18T20:23:45.000Z"
//   },
//   {
//     id: 810,
//     name: "Kolomoni MFB",
//     slug: "kolomoni-mfb-ng",
//     code: "899",
//     longcode: "090480",
//     gateway: "",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-11-20T18:56:06.000Z",
//     updatedAt: "2024-11-20T18:56:06.000Z"
//   },
//   {
//     id: 784,
//     name: "KONGAPAY (Kongapay Technologies Limited)(formerly Zinternet)",
//     slug: "kongapay-tech-ltd",
//     code: "100025",
//     longcode: "100025",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2024-07-05T13:00:17.000Z",
//     updatedAt: "2024-07-05T13:00:17.000Z"
//   },
//   {
//     id: 184,
//     name: "Kredi Money MFB LTD",
//     slug: "kredi-money-mfb",
//     code: "50200",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2021-08-11T09:54:03.000Z",
//     updatedAt: "2021-08-11T09:54:03.000Z"
//   },
//   {
//     id: 67,
//     name: "Kuda Bank",
//     slug: "kuda-bank",
//     code: "50211",
//     longcode: "",
//     gateway: "digitalbankmandate",
//     pay_with_bank: true,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2019-11-15T17:06:54.000Z",
//     updatedAt: "2024-10-29T10:56:03.000Z"
//   },
//   {
//     id: 109,
//     name: "Lagos Building Investment Company Plc.",
//     slug: "lbic-plc",
//     code: "90052",
//     longcode: "",
//     gateway: null,
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2020-08-10T15:07:44.000Z",
//     updatedAt: "2020-08-10T15:07:44.000Z"
//   },
//   {
//     id: 523,
//     name: "Letshego Microfinance Bank",
//     slug: "letshego-microfinance-bank",
//     code: "090420",
//     longcode: "090420",
//     gateway: "emandate",
//     pay_with_bank: false,
//     supports_transfer: true,
//     available_for_direct_debit: false,
//     active: true,
//     country: "Nigeria",
//     currency: "NGN",
//     type: "nuban",
//     is_deleted: false,
//     createdAt: "2022-07-28T14:22:56.000Z",
//     updatedAt: "2025-03-25T13:13:38.000Z"
//   },
//  ]






 export const NIGERIAN_BANKS = [
  { name: "78 Finance Company Ltd", code: "40195", slug: "78-finance-company-ltd-ng", longcode: "110072" },
  { name: "9mobile 9Payment Service Bank", code: "120001", slug: "9mobile-9payment-service-bank-ng", longcode: "120001" },
  { name: "Abbey Mortgage Bank", code: "404", slug: "abbey-mortgage-bank-ng", longcode: "" },
  { name: "Above Only MFB", code: "51204", slug: "above-only-mfb", longcode: "" },
  { name: "Abulesoro MFB", code: "51312", slug: "abulesoro-mfb-ng", longcode: "" },
  { name: "Access Bank", code: "044", slug: "access-bank", longcode: "044150149" },
  { name: "Access Bank (Diamond)", code: "063", slug: "access-bank-diamond", longcode: "063150162" },
  { name: "Accion Microfinance Bank", code: "602", slug: "accion-microfinance-bank-ng", longcode: "" },
  { name: "Aella MFB", code: "50315", slug: "aella-mfb-ng", longcode: "50315" },
  { name: "AG Mortgage Bank", code: "90077", slug: "ag-mortgage-bank-ng", longcode: "100028" },
  { name: "Ahmadu Bello University Microfinance Bank", code: "50036", slug: "ahmadu-bello-university-microfinance-bank-ng", longcode: "" },
  { name: "Airtel Smartcash PSB", code: "120004", slug: "airtel-smartcash-psb-ng", longcode: "120004" },
  { name: "AKU Microfinance Bank", code: "51336", slug: "aku-mfb", longcode: "" },
  { name: "Akuchukwu Microfinance Bank Limited", code: "090561", slug: "akuchukwu-microfinance-bank-limited-ng", longcode: "090561" },
  { name: "Al-Barakah Microfinance Bank", code: "50055", slug: "al-barakah-microfinance-bank-ng", longcode: "090133" },
  { name: "ALAT by WEMA", code: "035A", slug: "alat-by-wema", longcode: "035150103" },
  { name: "Alpha Morgan Bank", code: "108", slug: "alpha-morgan", longcode: "000041" },
  { name: "Alternative bank", code: "000304", slug: "the-alternative-bank-ng", longcode: "000304" },
  { name: "Amegy Microfinance Bank", code: "090629", slug: "amegy-microfinance-bank-ng", longcode: "090629" },
  { name: "Amju Unique MFB", code: "50926", slug: "amju-unique-mfb", longcode: "511080896" },
  { name: "Aramoko MFB", code: "50083", slug: "aramoko-mfb", longcode: "" },
  { name: "ASO Savings and Loans", code: "401", slug: "asosavings", longcode: "" },
  { name: "Assets Microfinance Bank", code: "50092", slug: "assets-microfinance-bank-ng", longcode: "50092" },
  { name: "Astrapolaris MFB LTD", code: "MFB50094", slug: "astrapolaris-mfb", longcode: "" },
  { name: "AVUENEGBE MICROFINANCE BANK", code: "090478", slug: "avuenegbe-microfinance-bank-ng", longcode: "090478" },
  { name: "AWACASH MICROFINANCE BANK", code: "51351", slug: "awacash-microfinance-bank-ng", longcode: "51351" },
  { name: "AZTEC MICROFINANCE BANK LIMITED", code: "51337", slug: "aztec-microfinance-bank-limited-ng", longcode: "090540" },
  { name: "Bainescredit MFB", code: "51229", slug: "bainescredit-mfb", longcode: "" },
  { name: "Banc Corp Microfinance Bank", code: "50117", slug: "banc-corp-microfinance-bank-ng", longcode: "50117" },
  { name: "BANKIT MICROFINANCE BANK LTD", code: "50572", slug: "bankit-microfinance-bank-ltd-ng", longcode: "090275" },
  { name: "BANKLY MFB", code: "51341", slug: "ampersand-microfinance-bank-ng", longcode: "" },
  { name: "Baobab Microfinance Bank", code: "MFB50992", slug: "baobab-microfinance-bank-ng", longcode: "MFB50992" },
  { name: "BellBank Microfinance Bank", code: "51100", slug: "bellbank-microfinance-bank-ng", longcode: "51100" },
  { name: "Benysta Microfinance Bank Limited", code: "51267", slug: "benysta-microfinance-bank-limited", longcode: "51267" },
  { name: "Beststar Microfinance Bank", code: "50123", slug: "beststar-microfinance-bank-ng", longcode: "090615" },
  { name: "BOLD MFB", code: "50725", slug: "bold-mfb-ng", longcode: "090753" },
  { name: "Bosak Microfinance Bank", code: "650", slug: "bosak-microfinance-bank-ng", longcode: "650" },
  { name: "Bowen Microfinance Bank", code: "50931", slug: "bowen-microfinance-bank", longcode: "" },
  { name: "Branch International Finance Company Limited", code: "FC40163", slug: "branch", longcode: "" },
  { name: "Brent Mortgage bank", code: "90070", slug: "brent-mortgage-bank-ng", longcode: "070015" },
  { name: "BuyPower MFB", code: "50645", slug: "buypower-mfb-ng", longcode: "50645" },
  { name: "Carbon", code: "565", slug: "carbon", longcode: "" },
  { name: "Cashbridge Microfinance Bank Limited", code: "51353", slug: "cashbridge-mfb-ng", longcode: "51353" },
  { name: "CASHCONNECT MFB", code: "865", slug: "cashconnect-mfb-ng", longcode: "865" },
  { name: "CEMCS Microfinance Bank", code: "50823", slug: "cemcs-microfinance-bank", longcode: "" },
  { name: "Chanelle Microfinance Bank Limited", code: "50171", slug: "chanelle-microfinance-bank-limited-ng", longcode: "50171" },
  { name: "Chikum Microfinance bank", code: "312", slug: "chikum-microfinance-bank-ng", longcode: null },
  { name: "Citibank Nigeria", code: "023", slug: "citibank-nigeria", longcode: "023150005" },
  { name: "CITYCODE MORTGAGE BANK", code: "070027", slug: "citycode-mortage-bank-ng", longcode: "070027" },
  { name: "Consumer Microfinance Bank", code: "50910", slug: "consumer-microfinance-bank-ng", longcode: "50910" },
  { name: "Cool Microfinance Bank Limited", code: "51458", slug: "cool-microfinance-bank-limited-ng", longcode: "090842" },
  { name: "Corestep MFB", code: "50204", slug: "corestep-mfb", longcode: "" },
  { name: "Coronation Merchant Bank", code: "559", slug: "coronation-merchant-bank-ng", longcode: "" },
  { name: "County Finance Limited", code: "FC40128", slug: "county-finance-limited", longcode: "" },
  { name: "Credit Direct Limited", code: "40119", slug: "credit-direct-limited-ng", longcode: "110049" },
  { name: "Crescent MFB", code: "51297", slug: "crescent-mfb", longcode: "" },
  { name: "Crust Microfinance Bank", code: "090560", slug: "crust-microfinance-bank-ng", longcode: "" },
  { name: "CRUTECH MICROFINANCE BANK LTD", code: "50216", slug: "crutech-microfinance-bank-ltd-ng", longcode: "090414" },
  { name: "Dash Microfinance Bank", code: "51368", slug: "dash-microfinance-bank-ng", longcode: "090845" },
  { name: "Davenport MICROFINANCE BANK", code: "51334", slug: "davenport-microfinance-bank-ng", longcode: "51334" },
  { name: "Dillon Microfinance Bank", code: "51450", slug: "dillon-microfinance-bank-ng", longcode: "09828" },
  { name: "Dot Microfinance Bank", code: "50162", slug: "dot-microfinance-bank-ng", longcode: "" },
  { name: "EBSU Microfinance Bank", code: "50922", slug: "ebsu-microfinance-bank-ng", longcode: "090427" },
  { name: "Ecobank Nigeria", code: "050", slug: "ecobank-nigeria", longcode: "050150010" },
  { name: "Ekimogun MFB", code: "50263", slug: "ekimogun-mfb-ng", longcode: "" },
  { name: "Ekondo Microfinance Bank", code: "098", slug: "ekondo-microfinance-bank-ng", longcode: "" },
  { name: "EXCEL FINANCE BANK", code: "090678", slug: "excel-finance-bank-ng", longcode: "090678" },
  { name: "Eyowo", code: "50126", slug: "eyowo", longcode: "" },
  { name: "Fairmoney Microfinance Bank", code: "51318", slug: "fairmoney-microfinance-bank-ng", longcode: "" },
  { name: "Fedeth MFB", code: "50298", slug: "fedeth-mfb-ng", longcode: "090482" },
  { name: "Fidelity Bank", code: "070", slug: "fidelity-bank", longcode: "070150003" },
  { name: "Firmus MFB", code: "51314", slug: "firmus-mfb", longcode: "" },
  { name: "First Bank of Nigeria", code: "011", slug: "first-bank-of-nigeria", longcode: "011151003" },
  { name: "First City Monument Bank", code: "214", slug: "first-city-monument-bank", longcode: "214150018" },
  { name: "FIRST ROYAL MICROFINANCE BANK", code: "090164", slug: "first-royal-microfinance-bank-ng", longcode: "090164" },
  { name: "FIRSTMIDAS MFB", code: "51333", slug: "firstmidas-mfb-ng", longcode: "090575" },
  { name: "FirstTrust Mortgage Bank Nigeria", code: "413", slug: "firsttrust-mortgage-bank-nigeria-ng", longcode: "" },
  { name: "FSDH Merchant Bank Limited", code: "501", slug: "fsdh-merchant-bank-limited", longcode: "" },
  { name: "FUTMINNA MICROFINANCE BANK", code: "832", slug: "futminna-microfinance-bank-ng", longcode: "832" },
  { name: "Garun Mallam MFB", code: "MFB51093", slug: "garun-mallam-mfb-ng", longcode: "MFB51093" },
  { name: "Gateway Mortgage Bank LTD", code: "812", slug: "gateway-mortgage-bank", longcode: "" },
  { name: "Globus Bank", code: "00103", slug: "globus-bank", longcode: "103015001" },
  { name: "Goldman MFB", code: "090574", slug: "goldman-mfb-ng", longcode: "950356" },
  { name: "GoMoney", code: "100022", slug: "gomoney", longcode: "" },
  { name: "GOOD SHEPHERD MICROFINANCE BANK", code: "090664", slug: "good-shepherd-microfinance-bank-ng", longcode: "090664" },
  { name: "Goodnews Microfinance Bank", code: "50739", slug: "goodnews-microfinance-bank-ng", longcode: "" },
  { name: "Greenwich Merchant Bank", code: "562", slug: "greenwich-merchant-bank-ng", longcode: "" },
  { name: "GROOMING MICROFINANCE BANK", code: "51276", slug: "grooming-microfinance-bank-ng", longcode: "51276" },
  { name: "GTI MFB", code: "50368", slug: "gti-mfb-ng", longcode: "090385" },
  { name: "Guaranty Trust Bank", code: "058", slug: "guaranty-trust-bank", longcode: "058152036" },
  { name: "Hackman Microfinance Bank", code: "51251", slug: "hackman-microfinance-bank", longcode: "" },
  { name: "Hasal Microfinance Bank", code: "50383", slug: "hasal-microfinance-bank", longcode: "" },
  { name: "Hayat Trust MFB", code: "51364", slug: "hayat-trust-mfb-ng", longcode: "090777" },
  { name: "HopePSB", code: "120002", slug: "hopepsb-ng", longcode: "120002" },
  { name: "IBANK Microfinance Bank", code: "51211", slug: "IBANK-mfb", longcode: "090115" },
  { name: "IBBU MFB", code: "51279", slug: "ibbu-mfb-ng", longcode: "51279" },
  { name: "Ibile Microfinance Bank", code: "51244", slug: "ibile-mfb", longcode: "" },
  { name: "Ibom Mortgage Bank", code: "90012", slug: "ibom-mortgage-bank-ng", longcode: "070025" },
  { name: "Ikoyi Osun MFB", code: "50439", slug: "ikoyi-osun-mfb", longcode: "" },
  { name: "Ilaro Poly Microfinance Bank", code: "50442", slug: "ilaro-poly-microfinance-bank-ng", longcode: "" },
  { name: "Imowo MFB", code: "50453", slug: "imowo-mfb-ng", longcode: "50453" },
  { name: "IMPERIAL HOMES MORTGAGE BANK", code: "415", slug: "imperial-homes-mortage-bank-ng", longcode: "100024" },
  { name: "INDULGE MFB", code: "51392", slug: "indulge-mfb-ng", longcode: "090772" },
  { name: "Infinity MFB", code: "50457", slug: "infinity-mfb", longcode: "" },
  { name: "Infinity trust Mortgage Bank", code: "070016", slug: "infinity-trust-mortgage-bank-ng", longcode: "070016" },
  { name: "ISUA MFB", code: "090701", slug: "isua-mfb-ng", longcode: "090701" },
  { name: "Jaiz Bank", code: "301", slug: "jaiz-bank", longcode: "301080020" },
  { name: "Kadpoly MFB", code: "50502", slug: "kadpoly-mfb", longcode: "" },
  { name: "KANOPOLY MFB", code: "51308", slug: "kanopoly-mfb-ng", longcode: "090592" },
  { name: "Kayvee Microfinance Bank", code: "5129", slug: "kayvee-microfinance-bank-ng", longcode: "090554" },
  { name: "Keystone Bank", code: "082", slug: "keystone-bank", longcode: "082150017" },
  { name: "Kolomoni MFB", code: "899", slug: "kolomoni-mfb-ng", longcode: "090480" },
  { name: "KONGAPAY", code: "100025", slug: "kongapay-tech-ltd", longcode: "100025" },
  { name: "Kredi Money MFB LTD", code: "50200", slug: "kredi-money-mfb", longcode: "" },
  { name: "Kuda Bank", code: "50211", slug: "kuda-bank", longcode: "" },
  { name: "Lagos Building Investment Company Plc.", code: "90052", slug: "lbic-plc", longcode: "" },
  { name: "Letshego Microfinance Bank", code: "090420", slug: "letshego-microfinance-bank", longcode: "090420" },
  { name: "Links MFB", code: "50549", slug: "links-mfb", longcode: "" },
  { name: "Living Trust Mortgage Bank", code: "031", slug: "living-trust-mortgage-bank", longcode: "" },
  { name: "LOMA MFB", code: "50491", slug: "loma-mfb-ng", longcode: "090620" },
  { name: "Lotus Bank", code: "303", slug: "lotus-bank", longcode: "" },
  { name: "Maal MFB", code: "51444", slug: "maal-mfb-ng", longcode: "" },
  { name: "MAINSTREET MICROFINANCE BANK", code: "090171", slug: "mainstreet-microfinance-bank-ng", longcode: "090171" },
  { name: "Mayfair MFB", code: "50563", slug: "mayfair-mfb", longcode: "" },
  { name: "Mint MFB", code: "50304", slug: "mint-mfb", longcode: "" },
  { name: "MINT-FINEX MFB", code: "09", slug: "mint-finex-mfb-ng", longcode: "090281" },
  { name: "Money Master PSB", code: "946", slug: "money-master-psb-ng", longcode: "" },
  { name: "Moniepoint MFB", code: "50515", slug: "moniepoint-mfb-ng", longcode: null },
  { name: "MTN Momo PSB", code: "120003", slug: "mtn-momo-psb-ng", longcode: "120003" },
  { name: "MUTUAL BENEFITS MICROFINANCE BANK", code: "090190", slug: "mutual-benefits-microfinance-bank-ng", longcode: "090190" },
  { name: "NDCC MICROFINANCE BANK", code: "090679", slug: "ndcc-microfinance-bank-ng", longcode: "090679" },
  { name: "NET MICROFINANCE BANK", code: "51361", slug: "net-microfinance-bank-ng", longcode: "51361" },
  { name: "Nigerian Navy Microfinance Bank Limited", code: "51142", slug: "nigerian-navy-microfinance-bank-limited-ng", longcode: "090263" },
  { name: "Nombank MFB", code: "50072", slug: "nombank-mfb-ng", longcode: "090645" },
  { name: "NOVA BANK", code: "561", slug: "nova-bank-ng", longcode: "060003" },
  { name: "Novus MFB", code: "51371", slug: "novus-mfb-ng", longcode: "090734" },
  { name: "NPF MICROFINANCE BANK", code: "50629", slug: "npf-microfinance-bank-ng", longcode: "50629" },
  { name: "NSUK MICROFINANCE BANK", code: "51261", slug: "nsuk-microfinanace-bank-ng", longcode: "090491" },
  { name: "Olabisi Onabanjo University Microfinance Bank", code: "50689", slug: "olabisi-onabanjo-university-microfinance-bank-ng", longcode: "090272" },
  { name: "OLUCHUKWU MICROFINANCE BANK LTD", code: "50697", slug: "oluchukwu-microfinance-bank-ltd-ng", longcode: "50697" },
  { name: "OPay Digital Services Limited (OPay)", code: "999992", slug: "paycom", longcode: "" },
  { name: "Optimus Bank Limited", code: "107", slug: "optimus-bank-ltd", longcode: "00107" },
  { name: "Paga", code: "100002", slug: "paga", longcode: "" },
  { name: "PalmPaystack-Titan", code: "100039", slug: "titan-paystack", longcode: "" },
  { name: "Peace Microfinance Bank", code: "50743", slug: "peace-microfinance-bank-ng", longcode: "50743" },
  { name: "PECANTRUST MICROFINANCE BANK LIMITED", code: "51226", slug: "pecantrust-microfinance-bank-limited-ng", longcode: "51226" },
  { name: "Personal Trust MFB", code: "51146", slug: "personal-trust-mfb-ng", longcode: "" },
  { name: "Petra Microfinance Bank Plc", code: "50746", slug: "petra-microfinance-bank-plc", longcode: "" },
  { name: "Pettysave MFB", code: "MFB51452", slug: "pettysave-mfb-ng", longcode: "090768" },
  { name: "PFI FINANCE COMPANY LIMITED", code: "050021", slug: "pfi-finance-company-limited-ng", longcode: "050021" },
  { name: "Platinum Mortgage Bank", code: "268", slug: "platinum-mortgage-bank-ng", longcode: null },
  { name: "Pocket App", code: "00716", slug: "pocket", longcode: "00716" },
  { name: "Polaris Bank", code: "076", slug: "polaris-bank", longcode: "076151006" },
  { name: "Polyunwana MFB", code: "50864", slug: "polyunwana-mfb-ng", longcode: null },
  { name: "PremiumTrust Bank", code: "105", slug: "premiumtrust-bank-ng", longcode: "000031" },
  { name: "Prospa Capital Microfinance Bank", code: "50739", slug: "prospa-capital-microfinance-bank-ng", longcode: "50739" },
  { name: "PROSPERIS FINANCE LIMITED", code: "050023", slug: "prosperis-finance-limited-ng", longcode: "050023" },
  { name: "Providus Bank", code: "101", slug: "providus-bank", longcode: "" },
  { name: "QuickFund MFB", code: "51293", slug: "quickfund-mfb", longcode: "" },
  { name: "Rand Merchant Bank", code: "502", slug: "rand-merchant-bank", longcode: "" },
  { name: "RANDALPHA MICROFINANCE BANK", code: "090496", slug: "randalpha-microfinance-bank-ng", longcode: "090496" },
  { name: "Refuge Mortgage Bank", code: "90067", slug: "refuge-mortgage-bank", longcode: "" },
  { name: "REHOBOTH MICROFINANCE BANK", code: "50761", slug: "rehoboth-microfinance-bank-ng", longcode: "090463" },
  { name: "Rephidim Microfinance Bank", code: "50994", slug: "rephidim", longcode: "221151615" },
  { name: "Rigo Microfinance Bank Limited", code: "51286", slug: "rigo-microfinance-bank-limited-ng", longcode: "51286" },
  { name: "ROCKSHIELD MICROFINANCE BANK", code: "50767", slug: "rockshield-microfinance-bank-ng", longcode: "" },
  { name: "Rubies MFB", code: "125", slug: "rubies-mfb", longcode: "" },
  { name: "Safe Haven MFB", code: "51113", slug: "safe-haven-mfb-ng", longcode: "51113" },
  { name: "SAGE GREY FINANCE LIMITED", code: "40165", slug: "sage-grey-finance-limited-ng", longcode: null },
  { name: "Shield MFB", code: "50582", slug: "shield-mfb-ng", longcode: "" },
  { name: "Signature Bank Ltd", code: "106", slug: "signature-bank-ltd-ng", longcode: "000034" },
  { name: "Solid Allianze MFB", code: "51062", slug: "solid-allianze-mfb", longcode: "" },
  { name: "Solid Rock MFB", code: "50800", slug: "solid-rock-mfb", longcode: "" },
  { name: "Sparkle Microfinance Bank", code: "51310", slug: "sparkle-microfinance-bank", longcode: "" },
  { name: "Springfield Microfinance Bank", code: "51429", slug: "springfield-microfinance-bank-ng", longcode: "090806" },
  { name: "Stanbic IBTC Bank", code: "221", slug: "stanbic-ibtc-bank", longcode: "221159522" },
  { name: "Standard Chartered Bank", code: "068", slug: "standard-chartered-bank", longcode: "068150015" },
  { name: "STANFORD MICROFINANCE BANK", code: "090162", slug: "stanford-microfinance-bank-ng", longcode: "090162" },
  { name: "STATESIDE MICROFINANCE BANK", code: "50809", slug: "stateside-microfinance-bank-ng", longcode: "50809" },
  { name: "STB Mortgage Bank", code: "070022", slug: "stb-mortgage-bank-ng", longcode: "070022" },
  { name: "Stellas MFB", code: "51253", slug: "stellas-mfb", longcode: "" },
  { name: "Sterling Bank", code: "232", slug: "sterling-bank", longcode: "232150016" },
  { name: "Summit Bank", code: "00305", slug: "summit-bank-ng", longcode: "080003" },
  { name: "Suntrust Bank", code: "100", slug: "suntrust-bank", longcode: "" },
  { name: "Supreme MFB", code: "50968", slug: "supreme-mfb-ng", longcode: "" },
  { name: "TAJ Bank", code: "302", slug: "taj-bank", longcode: "" },
  { name: "Tangerine Money", code: "51269", slug: "tangerine-money", longcode: "" },
  { name: "TENN", code: "51403", slug: "tenn-ng", longcode: "090716" },
  { name: "Think Finance Microfinance Bank", code: "677", slug: "think-finance-microfinance-bank-ng", longcode: "090373" },
  { name: "Titan Bank", code: "102", slug: "titan-bank", longcode: "" },
  { name: "TransPay MFB", code: "090708", slug: "transpay-mfb-ng", longcode: "090708" },
  { name: "TRUSTBANC J6 MICROFINANCE BANK", code: "51118", slug: "trustbanc-j6-microfinance-bank-ng", longcode: "090123" },
  { name: "U&C Microfinance Bank Ltd", code: "50840", slug: "uc-microfinance-bank-ltd-u-and-c-mfb-ng", longcode: "50840" },
  { name: "UCEE MFB", code: "090706", slug: "ucee-mfb-ng", longcode: "090706" },
  { name: "Uhuru MFB", code: "51322", slug: "uhuru-mfb-ng", longcode: "" },
  { name: "Ultraviolet Microfinance Bank", code: "51080", slug: "ultraviolet-microfinance-bank-ng", longcode: "090781" },
  { name: "Unaab Microfinance Bank Limited", code: "50870", slug: "unaab-microfinance-bank-limited-ng", longcode: "" },
  { name: "UNIABUJA MFB", code: "51447", slug: "uniabuja-mfb", longcode: "MFB51447" },
  { name: "Unical MFB", code: "50871", slug: "unical-mfb", longcode: "" },
  { name: "Unilag Microfinance Bank", code: "51316", slug: "unilag-microfinance-bank-ng", longcode: "" },
  { name: "UNIMAID MICROFINANCE BANK", code: "50875", slug: "unimaid-microfinance-bank-ng", longcode: "090464" },
  { name: "Union Bank of Nigeria", code: "032", slug: "union-bank-of-nigeria", longcode: "032080474" },
  { name: "United Bank For Africa", code: "033", slug: "united-bank-for-africa", longcode: "033153513" },
  { name: "Unity Bank", code: "215", slug: "unity-bank", longcode: "215154097" },
  { name: "Uzondu Microfinance Bank Awka Anambra State", code: "50894", slug: "uzondu-microfinance-bank-awka-anambra-state-ng", longcode: "50894" },
  { name: "Vale Finance Limited", code: "050020", slug: "vale-finance", longcode: "" },
  { name: "VFD Microfinance Bank Limited", code: "566", slug: "vfd", longcode: "" },
  { name: "Waya Microfinance Bank", code: "51355", slug: "waya-microfinance-bank-ng", longcode: "51355" },
  { name: "Wema Bank", code: "035", slug: "wema-bank", longcode: "035150103" },
  { name: "Weston Charis MFB", code: "51386", slug: "weston-charis-mfb-ng", longcode: "090741" },
  { name: "Xpress Wallet", code: "100040", slug: "xpress-wallet-ng", longcode: "100040" },
  { name: "Yes MFB", code: "594", slug: "yes-mfb-ng", longcode: "090142" },
  { name: "Zap", code: "00zap", slug: "zap", longcode: "00zap" },
  { name: "Zenith Bank", code: "057", slug: "zenith-bank", longcode: "057150013" },
  { name: "Zitra MFB", code: "51373", slug: "zitra-mfb-ng", longcode: "090718" }
];
    