const dstvPlans = [
  { name: "DStv Padi", coded: "dstv-padi", price: 4450.00, type: "dstv", status: 1, id: 877 },
  { name: "DStv Yanga", coded: "dstv-yanga", price: 6050.00, type: "dstv", status: 1, id: 878 },
  { name: "DStv Confam", coded: "dstv-confam", price: 11050.00, type: "dstv", status: 1, id: 879 },
  { name: "DStv Compact", coded: "dstv79", price: 19050.00, type: "dstv", status: 1, id: 880 },
  { name: "DStv Premium", coded: "dstv3", price: 44550.00, type: "dstv", status: 1, id: 881 },
  { name: "DStv Compact Plus", coded: "dstv7", price: 30050.00, type: "dstv", status: 1, id: 882 },
  { name: "DStv Premium-French", coded: "dstv9", price: 69050.00, type: "dstv", status: 1, id: 883 },
  { name: "DStv Premium-Asia", coded: "dstv10", price: 50550.00, type: "dstv", status: 1, id: 884 },
  { name: "DStv Confam + ExtraView", coded: "confam-extra", price: 17050.00, type: "dstv", status: 1, id: 885 },
  { name: "DStv Yanga + ExtraView", coded: "yanga-extra", price: 12050.00, type: "dstv", status: 1, id: 886 },
  { name: "DStv Padi + ExtraView", coded: "padi-extra", price: 10450.00, type: "dstv", status: 1, id: 887 },
  { name: "DStv Compact + Extra View", coded: "dstv30", price: 25050.00, type: "dstv", status: 1, id: 888 },
  { name: "DStv Compact + French Touch", coded: "com-frenchtouch", price: 26050.00, type: "dstv", status: 1, id: 889 },
  { name: "DStv Premium + Extra View", coded: "dstv33", price: 50550.00, type: "dstv", status: 1, id: 890 },
  { name: "DStv Compact + French Touch + ExtraView", coded: "com-frenchtouch-extra", price: 32050.00, type: "dstv", status: 1, id: 891 },
  { name: "DStv Compact Plus + French Plus", coded: "dstv43", price: 54550.00, type: "dstv", status: 1, id: 892 },
  { name: "DStv Compact Plus + French Touch", coded: "complus-frenchtouch", price: 37050.00, type: "dstv", status: 1, id: 893 },
  { name: "DStv Compact Plus + Extra View", coded: "dstv45", price: 36050.00, type: "dstv", status: 1, id: 894 },
  { name: "DStv Compact Plus + FrenchPlus + Extra View", coded: "complus-french-extraview", price: 60550.00, type: "dstv", status: 1, id: 895 },
  { name: "DStv Compact + French Plus", coded: "dstv47", price: 43550.00, type: "dstv", status: 1, id: 896 },
  { name: "DStv Premium + French + Extra View", coded: "dstv62", price: 75050.00, type: "dstv", status: 1, id: 897 },
  { name: "DStv French Plus Add-on", coded: "frenchplus-addon", price: 24550.00, type: "dstv", status: 1, id: 898 },
  { name: "DStv Great Wall Standalone Bouquet", coded: "dstv-greatwall", price: 3850.00, type: "dstv", status: 1, id: 899 },
  { name: "DStv French Touch Add-on", coded: "frenchtouch-addon", price: 7050.00, type: "dstv", status: 1, id: 900 },
  { name: "ExtraView Access", coded: "extraview-access", price: 6050.00, type: "dstv", status: 1, id: 901 },
  { name: "DStv Yanga + Showmax", coded: "dstv-yanga-showmax", price: 7800.00, type: "dstv", status: 1, id: 902 },
  { name: "DStv Great Wall Standalone Bouquet + Showmax", coded: "dstv-greatwall-showmax", price: 7350.00, type: "dstv", status: 1, id: 903 },
  { name: "DStv Compact Plus + Showmax", coded: "dstv-compact-plus-showmax", price: 31800.00, type: "dstv", status: 1, id: 904 },
  { name: "DStv Confam + Showmax", coded: "dstv-confam-showmax", price: 12800.00, type: "dstv", status: 1, id: 905 },
  { name: "DStv Compact + Showmax", coded: "dstv-compact-showmax", price: 20800.00, type: "dstv", status: 1, id: 906 },
  { name: "DStv Padi + Showmax", coded: "dstv-padi-showmax", price: 7950.00, type: "dstv", status: 1, id: 907 },
  { name: "DStv Asia + Showmax", coded: "dstv-asia-showmax", price: 18450.00, type: "dstv", status: 1, id: 908 },
  { name: "DStv Premium + French + Showmax", coded: "dstv-premium-french-showmax", price: 69050.00, type: "dstv", status: 1, id: 909 },
  { name: "DStv Premium + Showmax", coded: "dstv-premium-showmax", price: 44550.00, type: "dstv", status: 1, id: 910 },
  { name: "DStv Indian", coded: "dstv-indian", price: 14950.00, type: "dstv", status: 1, id: 911 },
  { name: "DStv Premium East Africa and Indian", coded: "dstv-premium-indian", price: 16580.00, type: "dstv", status: 1, id: 912 },
  { name: "DStv FTA Plus", coded: "dstv-fta-plus", price: 1650.00, type: "dstv", status: 1, id: 913 },
  { name: "DStv Premium HD", coded: "dstv-premium-hd", price: 39050.00, type: "dstv", status: 1, id: 914 },
  { name: "DStv Access", coded: "dstv-access-1", price: 2050.00, type: "dstv", status: 1, id: 915 },
  { name: "DStv Family", coded: "dstv-family-1", price: 4050.00, type: "dstv", status: 1, id: 916 },
  { name: "DStv India Add-on", coded: "dstv-indian-add-on", price: 14950.00, type: "dstv", status: 1, id: 917 },
  { name: "DSTV Mobile", coded: "dstv-mobile-1", price: 840.00, type: "dstv", status: 1, id: 918 },
  { name: "DStv Movie Bundle Add-on", coded: "dstv-movie-bundle-add-on", price: 3550.00, type: "dstv", status: 1, id: 919 },
  { name: "DStv PVR Access Service", coded: "dstv-pvr-access", price: 4050.00, type: "dstv", status: 1, id: 920 },
  { name: "DStv Premium W/Afr + Showmax", coded: "dstv-premium-wafr-showmax", price: 50550.00, type: "dstv", status: 1, id: 921 }
];

export default dstvPlans;